[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sphinxext-bsb"
description = "BSB Sphinx documentation extension"
version = "0.2.2"
dependencies = [
    "bsb-core~=4.0",
    "sphinx-design~=0.5"
]
